// Backup of original App.jsx for debugging — do not edit this file.
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Header from './components/Header';
import React, { useState, useEffect } from 'react';
import Footer from './components/Footer';
import Home1 from './pages/Home1';
import Home2Hero from './pages/Home2';
import AboutHero from './pages/aboutus';
import WelcomePage from './pages/welcome';
import AIHero from './pages/ResidentialProjects';
import RenovationServices from './pages/RenovationServices';  
import ProjectManagement from './pages/ProjectManagement';
import ResidentialProjects from './pages/ResidentialProjects';
import IndustrialProjects from './pages/IndustrialProjects';
import CommercialProjects from './pages/CommercialProjects';
import BlogHero from './pages/blog';
import BlogDetail from './pages/BlogDetail';
import ContactHero from './pages/contactus';
import UserDetailsSection from './pages/admindashboard'; //
import UserDashboard from './pages/userdashboard';
import ServicesHero from './pages/services';
import ScrollToTop from './pages/scroll-top';
import ArchitecturalDesigns from './pages/Architectural Designs';

function App() {
  const [lang, setLang] = useState('en');
  useEffect(() => {
    if (lang === 'ar' || lang === 'he') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [lang]);
  return (
    <BrowserRouter>
      <ScrollToTop />
      <div className="App">
        <Routes>
          {/* Redirect root to /welcome */}
          <Route path="/" element={<WelcomePage lang={lang} setLang={setLang} />} />
          <Route path="/welcome" element={<WelcomePage lang={lang} setLang={setLang} />} />
          {/* Admin Dashboard route without Header/Footer */}
          <Route path="/admindashboard" element={<UserDetailsSection lang={lang} />} />
          {/* All other routes with Header/Footer */}
          <Route
            path="/*"
            element={
              <>
                <Header lang={lang} setLang={setLang} />
                <Routes>
                  <Route path="home1" element={<Home1 lang={lang} />} />
                  <Route path="home2" element={<Home2Hero lang={lang} />} />
                  <Route path="aboutus" element={<AboutHero lang={lang} />} />
                  <Route path="Residential-Projects" element={<ResidentialProjects lang={lang} />} />
                  <Route path="Commercial-Projects" element={<CommercialProjects lang={lang} />} />
                  <Route path="Industrial-Projects" element={<IndustrialProjects lang={lang} />} />
                  <Route path="Renovation-Services" element={<RenovationServices lang={lang} />} />
                  <Route path="Architectural-Designs" element={<ArchitecturalDesigns lang={lang} />} />
                  <Route path="Project-Management" element={<ProjectManagement lang={lang} />} />
                  <Route path="services" element={<ServicesHero lang={lang} />} />
                  <Route path="blog" element={<BlogHero lang={lang} />} />
                  <Route path="/blog/:id" element={<BlogDetail lang={lang} />} />
                  <Route path="contactus" element={<ContactHero lang={lang} />} />
                  <Route path="/userdashboard" element={<UserDashboard lang={lang} />} />
                  {/* Add more routes as needed */}
                </Routes>
                <Footer lang={lang} />
              </>
            }
          />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

export default App;
